module.exports = {
    companies: [
        "3M",
        "ADM",
        "Aetna",
        "AIG",
        "Albertsons",
        "Allstate",
        "Alphabet",
        "Amazon",
        "American Airlines",
        "American Express",
        "Amerisourcebergen",
        "Andeavor",
        "Anthem",
        "Apple",
        "AT & T",
        "Bank of America",
        "Berkshire Hathaway",
        "Best Buy",
        "Boeing",
        "Cardinal Health",
        "Caterpillar",
        "Centene",
        "Charter Communications",
        "Chevron",
        "CHS",
        "CIGNA Corp",
        "Cisco",
        "Citigroup",
        "Coca - Cola",
        "ComCast",
        "ConocoPhillips",
        "Costco",
        "Costco",
        "CVS Health",
        "Dell Technologies",
        "Delta Air Lines",
        "Disney",
        "DowDuPont",
        "Energy Transfer Equity",
        "Exelon",
        "Express Scripts",
        "ExxonMobil",
        "Facebook",
        "Fannie Mae",
        "FedEx",
        "FedEx",
        "Ford",
        "Freddie Mac",
        "General Dynamics",
        "General Electric",
        "General Motors",
        "Goldman Sachs",
        "HCA",
        "Honeywell International",
        "HP",
        "Humana",
        "IBM",
        "Intel",
        "Johnson and Johnson",
        "JPMorgan Chase & Co.",
        "Kroger",
        "Liberty Mutual Insurance Group",
        "Lockheed Martin",
        "Lowes",
        "Lowe's",
        "Marathon Petroleum",
        "Massachusetts Mutual Life Insurance",
        "McKesson",
        "Merck & Co Inc",
        "MetLife",
        "Microsoft",
        "Morgan Stanley",
        "Nationwide",
        "New York Life Insurance",
        "Nike",
        "Oracle",
        "PepsiCo",
        "Pfizer",
        "Phillips 66",
        "Procter & Gamble",
        "Prudential",
        "Publix Super Markets",
        "Rite Aid",
        "State Farm",
        "SyncForce Client",
        "Sysco",
        "Target",
        "Tech Data",
        "The Home Depot",
        "TIAA",
        "Time Warner",
        "TJX Companies",
        "Tyson Foods",
        "United Continental Holdings",
        "United Health Group",
        "United Technologies",
        "UPS",
        "USAA",
        "Valero",
        "Verizon",
        "Walgreens Boots Alliance",
        "Walmart",
        "Wells Fargo",
        "World Fuel Services"
    ]
}